# Site settings
title: Machine Intelligence research in the Barnaghi Machine Intelligence Lab at Imperial College London
lab_name: Barnaghi Intelligence Lab
author: >
  Payam Barnaghi, Francesca Palermo and Barnaghi Machine Intelligence Lab
institution: Imperial College London
email: p.barnaghi@imperial.ac.uk
description: >
  Description-TBD
baseurl: ""
url: "https://barnaghi-machine-intelligence-lab.github.io/"
# twitter_username: 
# github_username:  
images_dir: "/images/"

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/

#plugins for search engine optimization
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
